### ISSUE TITLE
User Defined Dim Reduction

### ISSUE THREAD

**Issue by mpmorley** [dynverse/ti_slingshot#6]
For slingshot I think it would be helpful if the dim reductions provided by add_dimred() could be used rather than PCA.

**Comment by rcannood** [comment]
I agree, to some extent. You're referring to [this line of code](https://github.com/dynverse/ti_slingshot/blob/8976b83072b375d5f2a14bc4a388f0462937004c/package/R/ti_slingshot.R#L44), I suppose. The code used in ti_slingshot was provided by @kstreet13. 

@kstreet13: What do you think about changing this line of code to something like 
```
dyndimred::dimred(expression, method = parameters$dimred_method, ndim = parameters$ndim)
```
This would add another parameter to ti_slingshot, namely the dimred_method, for which the default would be PCA.

**Comment by kstreet13** [comment]
That sounds good! Our intention with Slingshot was to be somewhat agnostic to the upstream dimensionality reduction technique, so I think it would be good to have that extra flexibility.

**Comment by rcannood** [comment]
Hello @mpmorley,

This should be fixed now. You can specify a prior dimred as follows.

```r
library(tislingshot)
library(dyntoy)

dataset <- dyntoy::generate_dataset()

method <- tislingshot::ti_slingshot()

dataset$prior_information$dimred <- stats::prcomp(dataset$expression)$x[,1:5]

model <- dynwrap::infer_trajectory(dataset, method, give_priors = "dimred")
```

Let me know if this has not solved your issue.

Kind regards,
Robrecht
