### ISSUE TITLE
Error with given grouping

### ISSUE THREAD

**Issue by jingshuw** [dynverse/ti_slingshot#7]
Hello, 

I try to use ti_slingshot v2.0.0 so that I can give prior information to slingshot. However,  for the prior information groups_id, it seems not working whether I give a named character vector (as on the dynwrap::priors description) or a two-column data frame. 

If I give a named character vector, this is the error message I get even after I run library(tibble): 
```
Error in deframe(.) : could not find function "deframe"
Calls: <Anonymous> ... eval -> _fseq -> freduce -> withVisible -> <Anonymous>
Execution halted
```

If I give a two-column data frame, this is my error message:
```
Error in value[[3L]](cond) : Error produced in dynwrap input/output:
HDF5-API Errors:
    error #000: ../../../src/H5D.c in H5Dcreate2(): line 147: unable to create dataset
        class: HDF5
        major: Dataset
        minor: Unable to initialize object

    error #001: ../../../src/H5Dint.c in H5D__create_named(): line 494: unable to create and link to dataset
        class: HDF5
        major: Dataset
        minor: Unable to initialize object

    error #002: ../../../src/H5L.c in H5L_link_object(): line 1697: unable to create new link to object
        class: HDF5
        major: Links
        minor: Unable to initialize object

    error #003: ../../../src/H5L.c in H5L_create_real(): line 1941: can't insert link
        class: HDF5
        major: Symbol table
        minor: Unable to insert object

    error #004: ../../../src/H5Gtraverse.c in H5G_traverse(): line 869: internal path traversal failed
        class: HDF5
        major: Symbol table
        minor: Object not found

    error #005: 
```

Let me know if there are any solutions. Thanks a lot!

**Comment by rcannood** [comment]
Hello Jingshu,

Thanks for your report. This should be fixed now. Please run `docker pull dynverse/ti_slingshot:v2.0.0` and let me know if your issue is resolved.

Kind regards,
Robrecht

**Comment by jingshuw** [comment]
Hi Robrecht,

Thanks for your quick response. I indeed used ti_slingshot:v2.0.0, but still got the error. Should the groups_id prior information be a named vector or a two-column data frame?

Best,
Jingshu

**Comment by rcannood** [comment]
Oh, my bad, I missed the second half of your issue. The deframe issue should be fixed now, right?

Normally, both a character vector or a two-column data frame should do the trick.

Could you send me a minimal example which replicates your issue? Either a small dataset or the code to generate a small dataset would be fine, as well as the code you run to produce the error.

**Comment by jingshuw** [comment]
Thanks for your reply! with the new version ti_slingshot:v2.0.1, the error goes away and I can run my code successfully.
